if(${CMAKE_VERSION} VERSION_GREATER_EQUAL "3.21")
    set(CMAKE_C_STANDARD 17)
else()
    set(CMAKE_C_STANDARD 11)
endif()

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

if (CMAKE_CXX_COMPILER_ID MATCHES "GNU" OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    if (CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "aarch64")
        set(COMPILER_FLAG_VECTOR_EXTENSIONS "") #NEON is enabled on arm64
    else()
        set(COMPILER_FLAG_VECTOR_EXTENSIONS "-mavx")
    endif()
endif()


if (CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
    set(COMPILER_FLAG_VECTOR_EXTENSIONS "/arch:AVX")
endif()

add_compile_options(${COMPILER_FLAG_VECTOR_EXTENSIONS})